### PR TITLE
Insufficient Bandwidth

### LINKED ISSUE #618: Insufficient budget for bandwidth when downloading a small file
## Describe the bug
Downloading of large files (10+MB) runs without issues. The issue occurs when I try to download a small file (12KB).

## Expected behaviour
Able to download files of any size.

## Additional context
The file was uploaded with upload packing disabled.

### General Information
Are you running a fork of `renterd`? A fork synced to `origin/master` on September 21.
Are you on the mainnet or on the testnet? Mainnet.

### Renterd Config
Please provide us the following information:

**Autopilot Config**

```{
	"contracts": {
		"set": "autopilot",
		"amount": 20,
		"allowance": "1000000000000000000000000000",
		"period": 1008,
		"renewWindow": 302,
		"download": 100000000000,
		"upload": 10000000000,
		"storage": 10000000000
	},
	"hosts": {
		"allowRedundantIPs": false,
		"maxDowntimeHours": 1440,
		"scoreOverrides": null
	},
	"wallet": {
		"defragThreshold": 1000
	}
}
```

**Bus Config**

```{
	"minShards": 3,
	"totalShards": 9
}

{
	"hostBlockHeightLeeway": 6,
	"maxContractPrice": "1000000000000000000000000",
	"maxDownloadPrice": "1200000000000000000000000000",
	"maxRPCPrice": "1000000000000000000000",
	"maxStoragePrice": "69444444444",
	"maxUploadPrice": "100000000000000000000000000",
	"minAccountExpiry": 86400000000000,
	"minMaxCollateral": "10000000000000000000000000",
	"minMaxEphemeralAccountBalance": "1000000000000000000000000",
	"minPriceTableValidity": 300000000000
}
```

**Contract Set Contracts**

`20`

### Renterd Logs
```
2023-09-25T15:30:06+02:00	ERROR	downloadmanager	worker/download.go:332	download slab 0 failed: failed to download slab: completed=2, inflight=0, launched=9 downloaders=37 unused=0 errors=
aaf5aa89: ReadSector: ReadResponse: couldn't read subscription response: insufficient budget for bandwidth
74e99212: ReadSector: ReadResponse: couldn't read subscription response: insufficient budget for bandwidth
ab49fe30: ReadSector: ReadResponse: couldn't read subscription response: insufficient budget for bandwidth
6b4b7117: ReadSector: ReadResponse: couldn't read subscription response: insufficient budget for bandwidth
e534d338: ReadSector: ReadResponse: couldn't read subscription response: insufficient budget for bandwidth
23b0ee17: ReadSector: ReadResponse: couldn't read subscription response: insufficient budget for bandwidth
54a37a9c: ReadSector: ReadResponse: couldn't read subscription response: insufficient budget for bandwidth
```

### PR DESCRIPTION
**Pull request by peterjan**
This PR <https://github.com/SiaFoundation/renterd/pull/502> increased our download budget because some calls were failing due to the infamous "insufficient budget for bandwidth" error. I believe Chris added padding but for very small files it's not enough.

I added logging with price table details (hit me up if you are interested, there's no hidden or 0H costs that aren't dealt with) but decided to just increase the padding 🤷‍♂️ . We can simplify the expected read cost when the entire network has upgraded to `hostd`, it were pretty arbitrary over-estimates to begin with. Verified that it works on my node. 

This was actually an issue highlighted by the integrity checker also, added logging but hadn't gotten around investigating it more closely.

Fixes #618

### CODE REVIEW

File: worker/rhpv3.go [hunk 1]
```diff
@@ -674,7 +674,7 @@ func padBandwidth(pt rhpv3.HostPriceTable, rc rhpv3.ResourceCost) rhpv3.Resource
 	}
 	minPacketSize := uint64(1460)
 	minIngress := pt.UploadBandwidthCost.Mul64(minPacketSize)
-	minEgress := pt.DownloadBandwidthCost.Mul64(3 * minPacketSize)
+	minEgress := pt.DownloadBandwidthCost.Mul64(3*minPacketSize + responseLeeway)
```
Comment (peterjan) [inline worker/rhpv3.go:677]: Not sure where the 3 comes from here, was introduced by #502. Could've just made it `5` but decided to add the `responseLeeway` we use in `RPCReadSector`.. can be anything as long as it's higher. I was thinking of using a 4kib min. on both upload and download bandwidth... just didn't want to get rid of the packet size padding.

**Review by ChrisSchinnerl — APPROVED** [review]
