### PR TITLE
Extend migration failure alerts with affected objects

### LINKED ISSUE #845: Failed Migration Details
### Description

use ObjectsBySlabKey to decorate migration failures

### Version

_No response_

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

_No response_

### Anything else?

/

### PR DESCRIPTION
**Pull request by peterjan**
Closes #845

### CODE REVIEW

File: internal/test/e2e/migrations_test.go [hunk 1]
```diff
@@ -109,8 +109,70 @@ func TestMigrations(t *testing.T) {
...
+	tt.OK(b.CreateBucket(context.Background(), "newbucket", api.CreateBucketOptions{}))
+	tt.OKAll(w.UploadObject(context.Background(), bytes.NewReader(data), "newbucket", t.Name(), api.UploadObjectOptions{}))
+
+	// assert we currently don't have any alerts
+	ress, _ := b.Alerts(context.Background(), alerts.AlertsOpts{})
+	if ress.Totals.Error+ress.Totals.Critical != 0 {
+		t.Fatal("unexpected", ress)
+	}
+
+	// prepare
```
Comment (ChrisSchinnerl) [inline internal/test/e2e/migrations_test.go:128]: prepare?

File: internal/test/e2e/migrations_test.go [hunk 2]
```diff
@@ -109,8 +109,70 @@ func TestMigrations(t *testing.T) {
...
+
+	// remove all hosts to ensure migrations fail
+	for _, h := range cluster.hosts {
+		cluster.RemoveHost(h)
+	}
+
+	// fetch alerts and collect object ids until we found two
+	seen := make(map[types.Hash256]struct{})
```
Comment (ChrisSchinnerl) [inline internal/test/e2e/migrations_test.go:136]: I think you can clean the `Retry` up a bit by dropping this and just setting `got = make(map[string][]string` at the beginning of the retry.

File: internal/test/e2e/migrations_test.go [hunk 3]
```diff
@@ -109,8 +109,70 @@ func TestMigrations(t *testing.T) {
...
+	got := make(map[string][]string)
+	tt.Retry(100, 100*time.Millisecond, func() error {
+		ress, _ := b.Alerts(context.Background(), alerts.AlertsOpts{})
+		if ress.Totals.Error+ress.Totals.Critical == 0 {
```
Comment (ChrisSchinnerl) [inline internal/test/e2e/migrations_test.go:140]: This is redundant I think.

File: internal/test/e2e/migrations_test.go [hunk 4]
```diff
@@ -109,8 +109,70 @@ func TestMigrations(t *testing.T) {
...
+			if !ok {
+				continue
+			}
+
+			// collect all object ids per bucket
+			for bucket, ids := range data {
+				if objectIDs, ok := ids.([]interface{}); ok {
+					for _, id := range objectIDs {
+						got[bucket] = append(got[bucket], id.(string))
+						if len(got) == 2 {
```
Comment (ChrisSchinnerl) [inline internal/test/e2e/migrations_test.go:161]: I'd check for the length after the alert loop to make sure we are not accidentally aborting too early. There might be another object in which case the test should fail.

**Review by ChrisSchinnerl — APPROVED** [review]
