### PR TITLE
Make sure we use a valid price table when funding an account

### LINKED ISSUE #801: Failed to sync ephemeral account when no price table found
## Describe the bug
The autopilot fails to sync an EA when the host reports that no price table is found.
```
2023-12-07T10:41:57+01:00	ERROR	autopilot.accounts	autopilot/accounts.go:166	failed to sync account's balance: couldn't sync account: unable to fetch revision with contract: LatestRevision: ReadResponse: failed to read price table: no price table found
	{"accountID": "ed25519:486a8ec1183e1c85514e8c555d5f1280ea5c84274e3433bb8dced401ded8efe5", "hostKey": "ed25519:c235ba78d874a3906ff3db6afc2e364f9b77e805acbccc1f6ec61a91f0b238b2"}
```
There are also related errors. Looks like the latest revision can't be fetched for the same reason:
```
2023-12-07T11:04:22+01:00	ERROR	autopilot.accounts	autopilot/accounts.go:166	failed to sync account's balance: couldn't sync account: unable to fetch revision with contract: LatestRevision: ReadResponse: failed to read price table: no price table found
	{"accountID": "ed25519:46def458567cc80edcf45962317907e52dbacb560328e6c82b732011a524fea9", "hostKey": "ed25519:9501d2bc7d622f387c23630388e43339f02389aa45e709f9c5ef1a9ac51356b3"}
```
## Expected behaviour
If the host can't find the price table, a new price table should be requested.

## Additional context
The contracts were imported from the satellite, this is probably why no price table is found.

### General Information
Are you running a fork of `renterd`? Yes, but the errors appear on the `master` branch as well
Are you on the mainnet or on the testnet? Mainnet

### Renterd Config
Please provide us the following information:

**Autopilot Config**
```
{
	"contracts": {
		"set": "autopilot",
		"amount": 20,
		"allowance": "1000000000066666666666666667",
		"period": 1008,
		"renewWindow": 202,
		"download": 93333333333,
		"upload": 9333333333,
		"storage": 10000000000
	},
	"hosts": {
		"allowRedundantIPs": false,
		"maxDowntimeHours": 1440,
		"minRecentScanFailures": 10,
		"scoreOverrides": null
	},
	"wallet": {
		"defragThreshold": 1000
	}
}
```
**Bus Config**
```
{
	"minShards": 3,
	"totalShards": 9
}

{
	"hostBlockHeightLeeway": 6,
	"maxContractPrice": "1000000000000000000000000",
	"maxDownloadPrice": "1200000000000000000000000000",
	"maxRPCPrice": "1000000000000000000000",
	"maxStoragePrice": "69444444444",
	"maxUploadPrice": "100000000000000000000000000",
	"migrationSurchargeMultiplier": 10,
	"minAccountExpiry": 86400000000000,
	"minMaxCollateral": "10000000000000000000000000",
	"minMaxEphemeralAccountBalance": "1000000000000000000000000",
	"minPriceTableValidity": 300000000000
}
```
**Contract Set Contracts**
```
11
```
### Renterd Logs
If applicable, upload your `renterd.log` file or part of the file you think is relevant to the issue.

### PR DESCRIPTION
**Pull request by peterjan**
With this change I hope to get rid of the following error in the log. It does not happen a lot and it happens for the same host, causing me to believe it's simply due to the host being slow and connecting to it taking longer than whatever leeway we put on the price table validity.

```
{"level":"error","date":"2024-01-13T03:39:48Z","component":"autopilot.accounts","msg":"failed to fund account: couldn't fund account: failed to fund account with ~500.8 mS;FundAccount: ReadResponse: failed to read price table: no price table found\n","accountID":"ed25519:614c0fa737b04dc447d39c489c8911a9bfc614ec86897d90f0053c9be152cd3f","hostKey":"ed25519:fba406818f558676e117323f45665f3affbb10bb025f74548fafe66df0dd5274","balance":"499218792671999618136517","expected":"1 SC"}
```

Fixes #801

### CODE REVIEW

File: worker/host.go [hunk 1]
```diff
@@ -217,44 +217,56 @@ func (h *host) FetchPriceTable(ctx context.Context, rev *types.FileContractRevis
...
-		return fmt.Errorf("insufficient funds to fund account: %v <= %v", renterFunds, possibleFundCost)
-	} else if maxAmount := renterFunds.Sub(possibleFundCost); maxAmount.Cmp(amount) < 0 {
-		amount = maxAmount
-	}
 
 	return h.acc.WithDeposit(ctx, func() (types.Currency, error) {
-		return amount, h.transportPool.withTransportV3(ctx, h.hk, h.siamuxAddr, func(ctx context.Context, t *transportV3) (err error) {
-			cost := amount.Add(pt.FundAccountCost)
-			payment, err := payByContract(rev, cost, rhpv3.Account{}, h.renterKey) // no account needed for funding
+		deposit := balance.Sub(curr)
```
Comment (ChrisSchinnerl) [inline worker/host.go:232]: This is nicer directly under the `if curr.Cmp(balance) >= 0 {` check imo.

File: worker/host.go [hunk 2]
```diff
@@ -217,44 +217,56 @@ func (h *host) FetchPriceTable(ctx context.Context, rev *types.FileContractRevis
...
+			pt, err := h.priceTable(ctx, rev)
+			if err != nil {
+				return err
+			}
+
+			// check whether we have money left in the contract
+			if pt.FundAccountCost.Cmp(rev.ValidRenterPayout()) >= 0 {
+				return fmt.Errorf("insufficient funds to fund account: %v <= %v", rev.ValidRenterPayout(), pt.FundAccountCost)
+			}
+			funds := rev.ValidRenterPayout().Sub(pt.FundAccountCost)
```
Comment (ChrisSchinnerl) [inline worker/host.go:244]: Maybe call this `availableFunds`?

File: worker/host.go (hunk 1 above)
Comment (peterjan) [reply worker/host.go:232]: yeah went back and forth, will move

**Review by ChrisSchinnerl — APPROVED** [review]
